### ISSUE TITLE
Update write-up with source for w60x Micropython 1.19 codebase and release images

### ISSUE THREAD

**Issue by LexxM3** [sigmdel/w600_micropython_examples#1]
Thank you for your tutorial on the W600.  Your write-up is the most recent coverage and readily comes up in Google searches.  As a MAJOR service to your readers, it would be extremely (!!!) useful in your write-up to mention the modern (1.19 as recent as mid Nov 2022 build as of the end of 2022) Micropython codebase and release images being maintained by @robert-hh.  Specifically, the w60x codebase is here: https://github.com/robert-hh/micropython/tree/w60x (see w60x branch) and @robert-hh also maintains release images here: https://github.com/robert-hh/Shared-Stuff (see wm_w600_*.fls files).

**Comment by sigmdel** [comment]
Already knew about the MicroPython v1.19.1 port by Robert Hammelrath (robert-hh) but I was not aware that he made available release images... my bad :disappointed:.

Thank you very much LexxM3 for this information. You are quite right, it would be best for all to use the latest version.

Will update the blog post to include instructions on getting and downloading the current version of MicroPython as soon as possible. The rest of the post will be updated in the new year.

**Comment by sigmdel** [comment]
This repository now replaced by [w600_micropython_1_19_examples](https://github.com/sigmdel/w600_micropython_1_19_examples). Details in [A Second Look at the W600-PICO Development Board](https://sigmdel.ca/michel/ha/w600/second_look_w600_en.html).

**Comment by MartinsBastelstube** [comment]
With the MicroPython firmware v1.19.1, still can't get Neopixels to work on WeMOS W600-Pico boards.
As soon as I call NeoPixel.write(), all the connected Neopixels go to plain white at full steam (0xFFFFFF) -- no matter what colour pattern I have specified before.
Can you please give a code example that works on W600-Pico boards?

**Comment by robert-hh** [comment]
I know. At the moment, the timing works only for the slow version  of the NeoPixel devices. It is on my list to fix that and replace the implementation with the one used for SAMD21 or the slow STM32 devices.

**Comment by robert-hh** [comment]
I have updated the repository and the binary images at https://github.com/robert-hh/Shared-Stuff. That version works here with NeoPixel devices with the timing set to (400, 850, 850, 400).

**Comment by MartinsBastelstube** [comment]
In the Shared-stuff directory I found W600 firmware version 1.20, but the problem persists with that one.
-- or do I have to configure the timing parameters for the Neopixel driver? How would that work?

**Comment by robert-hh** [comment]
I uploaded the firmware again to SharedStuff after having tested  itwith a NeoPixel ring here. 
The timing parameters for NeoPixel have to be given as the third argument to the bitstream() call. These are (400, 850, 850, 400). But they are set in the neopixel.py lib script. The test code is below for  a 24 LED object. The NeoPixel run at 5V while the signal level of the W600 is at 3.3V. That's just at the limit, but most of the time it's fine.
```
import time
import machine, neopixel

def twims(np, delay):
    n = np.n
    np.fill((0,0,0))
    np.write()
    for j in range(1000):
        for k in range(n-1 , 0, -1):
            np[k] = np[k - 1]
        if (j % 8) < 2:
            np[0] = (255,0,0)
        else:
            np[0] = (0,0,10)
        np.write()
        time.sleep_ms(delay)

def run(delay=250, t = 1):
    np = neopixel.NeoPixel(machine.Pin(0, machine.Pin.OUT), 24, timing = t )
    try:
        twims(np, delay)
    except KeyboardInterrupt:
        np.fill((0, 0, 0))
        np.write()

run(250, 1)
```

**Comment by MartinsBastelstube** [comment]
Good -- with version 1.20.x I finally got the Neopixels working on the W600-Pico board. Thank you for the quick response and good support!
